# Generated by Django 2.1 on 2018-08-25 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
