# Generated by Django 2.1.1 on 2018-10-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_auto_20181019_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='print_flag',
            field=models.BooleanField(default=False),
        ),
    ]
