# Generated by Django 2.1 on 2018-08-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_auto_20180825_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='date',
            new_name='created',
        ),
    ]
