# Generated by Django 2.1.1 on 2018-10-25 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0003_queue_print_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='queue_app.Organization'),
        ),
    ]
