# Generated by Django 2.1 on 2018-08-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0004_auto_20180829_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['-created']},
        ),
    ]
