# Generated by Django 2.1.1 on 2018-11-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0005_auto_20181028_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='print_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
