# Generated by Django 2.1.1 on 2018-11-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('queue_app', '0007_auto_20181102_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
    ]
