# Generated by Django 2.1.1 on 2018-11-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('queue_app', '0008_service_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='service',
            name='group',
        ),
        migrations.AddField(
            model_name='counterbooth',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='booths', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='service',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='services', to='auth.Group'),
        ),
    ]
