# Generated by Django 2.1.1 on 2018-11-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0009_auto_20181103_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='character',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='queue_char',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
