# Generated by Django 2.1.1 on 2018-11-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('queue_app', '0011_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterbooth',
            name='groups',
        ),
        migrations.AddField(
            model_name='counterbooth',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='auth.Group'),
        ),
    ]
