# Generated by Django 2.1.1 on 2018-11-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0012_auto_20181112_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='booking_flag',
            new_name='is_booking',
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='call_flag',
            new_name='is_called',
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='print_flag',
            new_name='is_printed',
        ),
    ]
