# Generated by Django 2.1.1 on 2018-12-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0013_auto_20181122_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterbooth',
            name='name',
        ),
        migrations.AddField(
            model_name='counterbooth',
            name='display_name',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterbooth',
            name='spoken_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='desc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
