# Generated by Django 2.1.1 on 2018-10-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0013_auto_20181001_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
