# Generated by Django 2.1.1 on 2018-10-08 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queue_app', '0014_auto_20181001_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='booking_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queue',
            name='booking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queue',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
