# Generated by Django 2.1.1 on 2018-12-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('queue_app', '0014_auto_20181201_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='groups',
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='auth.Group'),
        ),
    ]
