# Generated by Django 2.1.1 on 2018-12-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0014_auto_20181201_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='queue_app.Organization'),
        ),
    ]
