# Generated by Django 2.1.1 on 2018-10-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0015_auto_20181008_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='booking_time',
            new_name='booking_datetime',
        ),
    ]
