# Generated by Django 2.1.1 on 2018-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0015_auto_20181205_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(blank=True, related_name='users', to='queue_app.Organization'),
        ),
    ]
