# Generated by Django 2.1.1 on 2018-12-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0016_auto_20181206_1405'),
        ('queue_app', '0015_auto_20181205_1741'),
    ]

    operations = [
    ]
