# Generated by Django 2.1.1 on 2018-12-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0017_merge_20181206_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterbooth',
            options={'verbose_name': 'counter booth', 'verbose_name_plural': 'counter booth'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organization'},
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['date_created'], 'verbose_name': 'queue', 'verbose_name_plural': 'queue'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'service'},
        ),
        migrations.AlterField(
            model_name='counterbooth',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='counterbooth',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_booth', to='queue_app.Organization'),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='queue_app.Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(related_name='users', to='queue_app.Organization'),
        ),
    ]
