# Generated by Django 2.2.1 on 2020-08-02 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0018_auto_20181216_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='finished'),
        ),
        migrations.AlterField(
            model_name='counterbooth',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='counterbooth',
            name='display_name',
            field=models.CharField(max_length=20, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='counterbooth',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='counterbooth',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_booth', to='queue_app.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='counterbooth',
            name='spoken_name',
            field=models.CharField(max_length=30, verbose_name='spoken name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='booking_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='booking date time'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='character',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='character'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='counter_booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='queue_app.CounterBooth', verbose_name='counter'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='is_booking',
            field=models.BooleanField(default=False, verbose_name='booking'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='is_called',
            field=models.BooleanField(default=False, verbose_name='called'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='printed'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='print_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='print date time'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='queue_app.Service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='auth.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='queue_app.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='service',
            name='queue_char',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='queue character'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(related_name='users', to='queue_app.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='phone number'),
        ),
    ]
