# Generated by Django 2.2.1 on 2020-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0019_auto_20200802_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
