# Generated by Django 2.2.1 on 2020-08-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0020_service_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='hide'),
        ),
    ]
